### ISSUE TITLE
Can I use this for Non-Code Projects?

### ISSUE THREAD

**Issue by PierrunoYT** [BCG-X-Official/agentkit#20]
Can I use this for Non-Code Projects?

**Comment by mastersplinter** [comment]
Can you be more specific? This is a software starter kit and the expectation is you would need to code and modify it to your use case.

This is distributed with an MIT License which is a permissive free software license. It allows users the freedom to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software, provided that the original copyright notice and permission notice are included in all copies or substantial portions of the software.

**Comment by mastersplinter** [comment]
Closing as I think the comment answers the question
