### ISSUE TITLE
failed to solve: changes out of order: "app/poetry.lock" ""

### ISSUE THREAD

**Issue by PaolaCartala** [BCG-X-Official/agentkit#23]
Im trying to execute:
`docker-compose -f docker-compose.yml up -d`
and i have the error:
`[+] Building 0.0s (0/0)  docker:default
[+] Building 1.1s (5/10)                                                                                                                                     docker:default
 => [fastapi_server internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 768B                                                                                                                                   0.0s 
 => [fastapi_server internal] load metadata for docker.io/tiangolo/uvicorn-gunicorn-fastapi:python3.10-slim-2022-11-25                                                 1.1s 
 => [fastapi_server internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                        0.0s 
 => [fastapi_server 1/6] FROM docker.io/tiangolo/uvicorn-gunicorn-fastapi:python3.10-slim-2022-11-25@sha256:22589c7d5ce3755fc43e78496744c57e322581cc05d0c15421cada291  0.0s 
 => ERROR [fastapi_server internal] load build context                                                                                                                 0.0s 
 => => transferring context: 36B                                                                                                                                       0.0s 
------
 > [fastapi_server internal] load build context:
------
failed to solve: changes out of order: "app/poetry.lock" ""`

**Comment by mastersplinter** [comment]
@PaolaCartala please clear your Docker Cache and report if this issue still occurs

**Comment by PaolaCartala** [comment]
It still happens, with a clean docker cache and even after a reinstallation of Docker

**Comment by drivian** [comment]
Hi @PaolaCartala this is related to an issue with Docker: https://github.com/docker/compose/issues/11421
 
Recommend downgrading docker to 4.26.1 or by following the direction of MichelZ:

Replace the docker-compose.exe with the one from:
[v2.24.5 (release)](https://github.com/docker/compose/releases/tag/v2.24.5)
([v2.24.5 docker-compose-windows-x86_64.exe (download)](https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-windows-x86_64.exe))
in:

**Comment by mastersplinter** [comment]
This is an issue with the latest version of Docker, a fix is detailed here  https://github.com/docker/compose/issues/11421
